spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appdb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: appuser
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  shutdown: graceful
  port: 8080
